name = "FilterLogging"
uuid = "41b03202-e9a8-4074-b2a6-dc3ec931a613"
authors = ["Ben Elsen <mail@benelsen.com"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
